<?php
namespace ProbePerfIntRangeReturn;
function guard(int $i): void {
	if ($i === 3) { return; }
	if ($i === 6) { return; }
	if ($i === 9) { return; }
	if ($i === 12) { return; }
	if ($i === 15) { return; }
	if ($i === 18) { return; }
	if ($i === 21) { return; }
	if ($i === 24) { return; }
	if ($i === 27) { return; }
	if ($i === 30) { return; }
	if ($i === 33) { return; }
	if ($i === 36) { return; }
	if ($i === 39) { return; }
	if ($i === 42) { return; }
	if ($i === 45) { return; }
	if ($i === 48) { return; }
	if ($i === 51) { return; }
	if ($i === 54) { return; }
	if ($i === 57) { return; }
	if ($i === 60) { return; }
	if ($i === 63) { return; }
	if ($i === 66) { return; }
	if ($i === 69) { return; }
	if ($i === 72) { return; }
	if ($i === 75) { return; }
	if ($i === 78) { return; }
	if ($i === 81) { return; }
	if ($i === 84) { return; }
	if ($i === 87) { return; }
	if ($i === 90) { return; }
	if ($i === 93) { return; }
	if ($i === 96) { return; }
	if ($i === 99) { return; }
	if ($i === 102) { return; }
	if ($i === 105) { return; }
	if ($i === 108) { return; }
	if ($i === 111) { return; }
	if ($i === 114) { return; }
	if ($i === 117) { return; }
	if ($i === 120) { return; }
	if ($i === 123) { return; }
	if ($i === 126) { return; }
	if ($i === 129) { return; }
	if ($i === 132) { return; }
	if ($i === 135) { return; }
	if ($i === 138) { return; }
	if ($i === 141) { return; }
	if ($i === 144) { return; }
	if ($i === 147) { return; }
	if ($i === 150) { return; }
	if ($i === 153) { return; }
	if ($i === 156) { return; }
	if ($i === 159) { return; }
	if ($i === 162) { return; }
	if ($i === 165) { return; }
	if ($i === 168) { return; }
	if ($i === 171) { return; }
	if ($i === 174) { return; }
	if ($i === 177) { return; }
	if ($i === 180) { return; }
	if ($i === 183) { return; }
	if ($i === 186) { return; }
	if ($i === 189) { return; }
	if ($i === 192) { return; }
	if ($i === 195) { return; }
	if ($i === 198) { return; }
	if ($i === 201) { return; }
	if ($i === 204) { return; }
	if ($i === 207) { return; }
	if ($i === 210) { return; }
	if ($i === 213) { return; }
	if ($i === 216) { return; }
	if ($i === 219) { return; }
	if ($i === 222) { return; }
	if ($i === 225) { return; }
	if ($i === 228) { return; }
	if ($i === 231) { return; }
	if ($i === 234) { return; }
	if ($i === 237) { return; }
	if ($i === 240) { return; }
	if ($i === 243) { return; }
	if ($i === 246) { return; }
	if ($i === 249) { return; }
	if ($i === 252) { return; }
	if ($i === 255) { return; }
	if ($i === 258) { return; }
	if ($i === 261) { return; }
	if ($i === 264) { return; }
	if ($i === 267) { return; }
	if ($i === 270) { return; }
	if ($i === 273) { return; }
	if ($i === 276) { return; }
	if ($i === 279) { return; }
	if ($i === 282) { return; }
	if ($i === 285) { return; }
	if ($i === 288) { return; }
	if ($i === 291) { return; }
	if ($i === 294) { return; }
	if ($i === 297) { return; }
	if ($i === 300) { return; }
	if ($i === 303) { return; }
	if ($i === 306) { return; }
	if ($i === 309) { return; }
	if ($i === 312) { return; }
	if ($i === 315) { return; }
	if ($i === 318) { return; }
	if ($i === 321) { return; }
	if ($i === 324) { return; }
	if ($i === 327) { return; }
	if ($i === 330) { return; }
	if ($i === 333) { return; }
	if ($i === 336) { return; }
	if ($i === 339) { return; }
	if ($i === 342) { return; }
	if ($i === 345) { return; }
	if ($i === 348) { return; }
	if ($i === 351) { return; }
	if ($i === 354) { return; }
	if ($i === 357) { return; }
	if ($i === 360) { return; }
	if ($i === 363) { return; }
	if ($i === 366) { return; }
	if ($i === 369) { return; }
	if ($i === 372) { return; }
	if ($i === 375) { return; }
	if ($i === 378) { return; }
	if ($i === 381) { return; }
	if ($i === 384) { return; }
	if ($i === 387) { return; }
	if ($i === 390) { return; }
	if ($i === 393) { return; }
	if ($i === 396) { return; }
	if ($i === 399) { return; }
	if ($i === 402) { return; }
	if ($i === 405) { return; }
	if ($i === 408) { return; }
	if ($i === 411) { return; }
	if ($i === 414) { return; }
	if ($i === 417) { return; }
	if ($i === 420) { return; }
	if ($i === 423) { return; }
	if ($i === 426) { return; }
	if ($i === 429) { return; }
	if ($i === 432) { return; }
	if ($i === 435) { return; }
	if ($i === 438) { return; }
	if ($i === 441) { return; }
	if ($i === 444) { return; }
	if ($i === 447) { return; }
	if ($i === 450) { return; }
	if ($i === 453) { return; }
	if ($i === 456) { return; }
	if ($i === 459) { return; }
	if ($i === 462) { return; }
	if ($i === 465) { return; }
	if ($i === 468) { return; }
	if ($i === 471) { return; }
	if ($i === 474) { return; }
	if ($i === 477) { return; }
	if ($i === 480) { return; }
	if ($i === 483) { return; }
	if ($i === 486) { return; }
	if ($i === 489) { return; }
	if ($i === 492) { return; }
	if ($i === 495) { return; }
	if ($i === 498) { return; }
	if ($i === 501) { return; }
	if ($i === 504) { return; }
	if ($i === 507) { return; }
	if ($i === 510) { return; }
	if ($i === 513) { return; }
	if ($i === 516) { return; }
	if ($i === 519) { return; }
	if ($i === 522) { return; }
	if ($i === 525) { return; }
	if ($i === 528) { return; }
	if ($i === 531) { return; }
	if ($i === 534) { return; }
	if ($i === 537) { return; }
	if ($i === 540) { return; }
	if ($i === 543) { return; }
	if ($i === 546) { return; }
	if ($i === 549) { return; }
	if ($i === 552) { return; }
	if ($i === 555) { return; }
	if ($i === 558) { return; }
	if ($i === 561) { return; }
	if ($i === 564) { return; }
	if ($i === 567) { return; }
	if ($i === 570) { return; }
	if ($i === 573) { return; }
	if ($i === 576) { return; }
	if ($i === 579) { return; }
	if ($i === 582) { return; }
	if ($i === 585) { return; }
	if ($i === 588) { return; }
	if ($i === 591) { return; }
	if ($i === 594) { return; }
	if ($i === 597) { return; }
	if ($i === 600) { return; }
	if ($i === 603) { return; }
	if ($i === 606) { return; }
	if ($i === 609) { return; }
	if ($i === 612) { return; }
	if ($i === 615) { return; }
	if ($i === 618) { return; }
	if ($i === 621) { return; }
	if ($i === 624) { return; }
	if ($i === 627) { return; }
	if ($i === 630) { return; }
	if ($i === 633) { return; }
	if ($i === 636) { return; }
	if ($i === 639) { return; }
	if ($i === 642) { return; }
	if ($i === 645) { return; }
	if ($i === 648) { return; }
	if ($i === 651) { return; }
	if ($i === 654) { return; }
	if ($i === 657) { return; }
	if ($i === 660) { return; }
	if ($i === 663) { return; }
	if ($i === 666) { return; }
	if ($i === 669) { return; }
	if ($i === 672) { return; }
	if ($i === 675) { return; }
	if ($i === 678) { return; }
	if ($i === 681) { return; }
	if ($i === 684) { return; }
	if ($i === 687) { return; }
	if ($i === 690) { return; }
	if ($i === 693) { return; }
	if ($i === 696) { return; }
	if ($i === 699) { return; }
	if ($i === 702) { return; }
	if ($i === 705) { return; }
	if ($i === 708) { return; }
	if ($i === 711) { return; }
	if ($i === 714) { return; }
	if ($i === 717) { return; }
	if ($i === 720) { return; }
	if ($i === 723) { return; }
	if ($i === 726) { return; }
	if ($i === 729) { return; }
	if ($i === 732) { return; }
	if ($i === 735) { return; }
	if ($i === 738) { return; }
	if ($i === 741) { return; }
	if ($i === 744) { return; }
	if ($i === 747) { return; }
	if ($i === 750) { return; }
	if ($i === 753) { return; }
	if ($i === 756) { return; }
	if ($i === 759) { return; }
	if ($i === 762) { return; }
	if ($i === 765) { return; }
	if ($i === 768) { return; }
	if ($i === 771) { return; }
	if ($i === 774) { return; }
	if ($i === 777) { return; }
	if ($i === 780) { return; }
	if ($i === 783) { return; }
	if ($i === 786) { return; }
	if ($i === 789) { return; }
	if ($i === 792) { return; }
	if ($i === 795) { return; }
	if ($i === 798) { return; }
	if ($i === 801) { return; }
	if ($i === 804) { return; }
	if ($i === 807) { return; }
	if ($i === 810) { return; }
	if ($i === 813) { return; }
	if ($i === 816) { return; }
	if ($i === 819) { return; }
	if ($i === 822) { return; }
	if ($i === 825) { return; }
	if ($i === 828) { return; }
	if ($i === 831) { return; }
	if ($i === 834) { return; }
	if ($i === 837) { return; }
	if ($i === 840) { return; }
	if ($i === 843) { return; }
	if ($i === 846) { return; }
	if ($i === 849) { return; }
	if ($i === 852) { return; }
	if ($i === 855) { return; }
	if ($i === 858) { return; }
	if ($i === 861) { return; }
	if ($i === 864) { return; }
	if ($i === 867) { return; }
	if ($i === 870) { return; }
	if ($i === 873) { return; }
	if ($i === 876) { return; }
	if ($i === 879) { return; }
	if ($i === 882) { return; }
	if ($i === 885) { return; }
	if ($i === 888) { return; }
	if ($i === 891) { return; }
	if ($i === 894) { return; }
	if ($i === 897) { return; }
	if ($i === 900) { return; }
	\PHPStan\dumpType($i);
}
