<?php
namespace ProbePerfInt;
function guard(int $i): void {
	if ($i === 1) { return; }
	if ($i === 2) { return; }
	if ($i === 3) { return; }
	if ($i === 4) { return; }
	if ($i === 5) { return; }
	if ($i === 6) { return; }
	if ($i === 7) { return; }
	if ($i === 8) { return; }
	if ($i === 9) { return; }
	if ($i === 10) { return; }
	if ($i === 11) { return; }
	if ($i === 12) { return; }
	if ($i === 13) { return; }
	if ($i === 14) { return; }
	if ($i === 15) { return; }
	if ($i === 16) { return; }
	if ($i === 17) { return; }
	if ($i === 18) { return; }
	if ($i === 19) { return; }
	if ($i === 20) { return; }
	if ($i === 21) { return; }
	if ($i === 22) { return; }
	if ($i === 23) { return; }
	if ($i === 24) { return; }
	if ($i === 25) { return; }
	if ($i === 26) { return; }
	if ($i === 27) { return; }
	if ($i === 28) { return; }
	if ($i === 29) { return; }
	if ($i === 30) { return; }
	if ($i === 31) { return; }
	if ($i === 32) { return; }
	if ($i === 33) { return; }
	if ($i === 34) { return; }
	if ($i === 35) { return; }
	if ($i === 36) { return; }
	if ($i === 37) { return; }
	if ($i === 38) { return; }
	if ($i === 39) { return; }
	if ($i === 40) { return; }
	if ($i === 41) { return; }
	if ($i === 42) { return; }
	if ($i === 43) { return; }
	if ($i === 44) { return; }
	if ($i === 45) { return; }
	if ($i === 46) { return; }
	if ($i === 47) { return; }
	if ($i === 48) { return; }
	if ($i === 49) { return; }
	if ($i === 50) { return; }
	if ($i === 51) { return; }
	if ($i === 52) { return; }
	if ($i === 53) { return; }
	if ($i === 54) { return; }
	if ($i === 55) { return; }
	if ($i === 56) { return; }
	if ($i === 57) { return; }
	if ($i === 58) { return; }
	if ($i === 59) { return; }
	if ($i === 60) { return; }
	if ($i === 61) { return; }
	if ($i === 62) { return; }
	if ($i === 63) { return; }
	if ($i === 64) { return; }
	if ($i === 65) { return; }
	if ($i === 66) { return; }
	if ($i === 67) { return; }
	if ($i === 68) { return; }
	if ($i === 69) { return; }
	if ($i === 70) { return; }
	if ($i === 71) { return; }
	if ($i === 72) { return; }
	if ($i === 73) { return; }
	if ($i === 74) { return; }
	if ($i === 75) { return; }
	if ($i === 76) { return; }
	if ($i === 77) { return; }
	if ($i === 78) { return; }
	if ($i === 79) { return; }
	if ($i === 80) { return; }
	if ($i === 81) { return; }
	if ($i === 82) { return; }
	if ($i === 83) { return; }
	if ($i === 84) { return; }
	if ($i === 85) { return; }
	if ($i === 86) { return; }
	if ($i === 87) { return; }
	if ($i === 88) { return; }
	if ($i === 89) { return; }
	if ($i === 90) { return; }
	if ($i === 91) { return; }
	if ($i === 92) { return; }
	if ($i === 93) { return; }
	if ($i === 94) { return; }
	if ($i === 95) { return; }
	if ($i === 96) { return; }
	if ($i === 97) { return; }
	if ($i === 98) { return; }
	if ($i === 99) { return; }
	if ($i === 100) { return; }
	if ($i === 101) { return; }
	if ($i === 102) { return; }
	if ($i === 103) { return; }
	if ($i === 104) { return; }
	if ($i === 105) { return; }
	if ($i === 106) { return; }
	if ($i === 107) { return; }
	if ($i === 108) { return; }
	if ($i === 109) { return; }
	if ($i === 110) { return; }
	if ($i === 111) { return; }
	if ($i === 112) { return; }
	if ($i === 113) { return; }
	if ($i === 114) { return; }
	if ($i === 115) { return; }
	if ($i === 116) { return; }
	if ($i === 117) { return; }
	if ($i === 118) { return; }
	if ($i === 119) { return; }
	if ($i === 120) { return; }
	if ($i === 121) { return; }
	if ($i === 122) { return; }
	if ($i === 123) { return; }
	if ($i === 124) { return; }
	if ($i === 125) { return; }
	if ($i === 126) { return; }
	if ($i === 127) { return; }
	if ($i === 128) { return; }
	if ($i === 129) { return; }
	if ($i === 130) { return; }
	if ($i === 131) { return; }
	if ($i === 132) { return; }
	if ($i === 133) { return; }
	if ($i === 134) { return; }
	if ($i === 135) { return; }
	if ($i === 136) { return; }
	if ($i === 137) { return; }
	if ($i === 138) { return; }
	if ($i === 139) { return; }
	if ($i === 140) { return; }
	if ($i === 141) { return; }
	if ($i === 142) { return; }
	if ($i === 143) { return; }
	if ($i === 144) { return; }
	if ($i === 145) { return; }
	if ($i === 146) { return; }
	if ($i === 147) { return; }
	if ($i === 148) { return; }
	if ($i === 149) { return; }
	if ($i === 150) { return; }
	if ($i === 151) { return; }
	if ($i === 152) { return; }
	if ($i === 153) { return; }
	if ($i === 154) { return; }
	if ($i === 155) { return; }
	if ($i === 156) { return; }
	if ($i === 157) { return; }
	if ($i === 158) { return; }
	if ($i === 159) { return; }
	if ($i === 160) { return; }
	if ($i === 161) { return; }
	if ($i === 162) { return; }
	if ($i === 163) { return; }
	if ($i === 164) { return; }
	if ($i === 165) { return; }
	if ($i === 166) { return; }
	if ($i === 167) { return; }
	if ($i === 168) { return; }
	if ($i === 169) { return; }
	if ($i === 170) { return; }
	if ($i === 171) { return; }
	if ($i === 172) { return; }
	if ($i === 173) { return; }
	if ($i === 174) { return; }
	if ($i === 175) { return; }
	if ($i === 176) { return; }
	if ($i === 177) { return; }
	if ($i === 178) { return; }
	if ($i === 179) { return; }
	if ($i === 180) { return; }
	if ($i === 181) { return; }
	if ($i === 182) { return; }
	if ($i === 183) { return; }
	if ($i === 184) { return; }
	if ($i === 185) { return; }
	if ($i === 186) { return; }
	if ($i === 187) { return; }
	if ($i === 188) { return; }
	if ($i === 189) { return; }
	if ($i === 190) { return; }
	if ($i === 191) { return; }
	if ($i === 192) { return; }
	if ($i === 193) { return; }
	if ($i === 194) { return; }
	if ($i === 195) { return; }
	if ($i === 196) { return; }
	if ($i === 197) { return; }
	if ($i === 198) { return; }
	if ($i === 199) { return; }
	if ($i === 200) { return; }
	if ($i === 201) { return; }
	if ($i === 202) { return; }
	if ($i === 203) { return; }
	if ($i === 204) { return; }
	if ($i === 205) { return; }
	if ($i === 206) { return; }
	if ($i === 207) { return; }
	if ($i === 208) { return; }
	if ($i === 209) { return; }
	if ($i === 210) { return; }
	if ($i === 211) { return; }
	if ($i === 212) { return; }
	if ($i === 213) { return; }
	if ($i === 214) { return; }
	if ($i === 215) { return; }
	if ($i === 216) { return; }
	if ($i === 217) { return; }
	if ($i === 218) { return; }
	if ($i === 219) { return; }
	if ($i === 220) { return; }
	if ($i === 221) { return; }
	if ($i === 222) { return; }
	if ($i === 223) { return; }
	if ($i === 224) { return; }
	if ($i === 225) { return; }
	if ($i === 226) { return; }
	if ($i === 227) { return; }
	if ($i === 228) { return; }
	if ($i === 229) { return; }
	if ($i === 230) { return; }
	if ($i === 231) { return; }
	if ($i === 232) { return; }
	if ($i === 233) { return; }
	if ($i === 234) { return; }
	if ($i === 235) { return; }
	if ($i === 236) { return; }
	if ($i === 237) { return; }
	if ($i === 238) { return; }
	if ($i === 239) { return; }
	if ($i === 240) { return; }
	if ($i === 241) { return; }
	if ($i === 242) { return; }
	if ($i === 243) { return; }
	if ($i === 244) { return; }
	if ($i === 245) { return; }
	if ($i === 246) { return; }
	if ($i === 247) { return; }
	if ($i === 248) { return; }
	if ($i === 249) { return; }
	if ($i === 250) { return; }
	if ($i === 251) { return; }
	if ($i === 252) { return; }
	if ($i === 253) { return; }
	if ($i === 254) { return; }
	if ($i === 255) { return; }
	if ($i === 256) { return; }
	if ($i === 257) { return; }
	if ($i === 258) { return; }
	if ($i === 259) { return; }
	if ($i === 260) { return; }
	if ($i === 261) { return; }
	if ($i === 262) { return; }
	if ($i === 263) { return; }
	if ($i === 264) { return; }
	if ($i === 265) { return; }
	if ($i === 266) { return; }
	if ($i === 267) { return; }
	if ($i === 268) { return; }
	if ($i === 269) { return; }
	if ($i === 270) { return; }
	if ($i === 271) { return; }
	if ($i === 272) { return; }
	if ($i === 273) { return; }
	if ($i === 274) { return; }
	if ($i === 275) { return; }
	if ($i === 276) { return; }
	if ($i === 277) { return; }
	if ($i === 278) { return; }
	if ($i === 279) { return; }
	if ($i === 280) { return; }
	if ($i === 281) { return; }
	if ($i === 282) { return; }
	if ($i === 283) { return; }
	if ($i === 284) { return; }
	if ($i === 285) { return; }
	if ($i === 286) { return; }
	if ($i === 287) { return; }
	if ($i === 288) { return; }
	if ($i === 289) { return; }
	if ($i === 290) { return; }
	if ($i === 291) { return; }
	if ($i === 292) { return; }
	if ($i === 293) { return; }
	if ($i === 294) { return; }
	if ($i === 295) { return; }
	if ($i === 296) { return; }
	if ($i === 297) { return; }
	if ($i === 298) { return; }
	if ($i === 299) { return; }
	if ($i === 300) { return; }
	\PHPStan\dumpType($i);
}
