<?php
namespace ProbePerfIntGap;
function guard(int $i): void {
	if ($i === 2) { return; }
	if ($i === 4) { return; }
	if ($i === 6) { return; }
	if ($i === 8) { return; }
	if ($i === 10) { return; }
	if ($i === 12) { return; }
	if ($i === 14) { return; }
	if ($i === 16) { return; }
	if ($i === 18) { return; }
	if ($i === 20) { return; }
	if ($i === 22) { return; }
	if ($i === 24) { return; }
	if ($i === 26) { return; }
	if ($i === 28) { return; }
	if ($i === 30) { return; }
	if ($i === 32) { return; }
	if ($i === 34) { return; }
	if ($i === 36) { return; }
	if ($i === 38) { return; }
	if ($i === 40) { return; }
	if ($i === 42) { return; }
	if ($i === 44) { return; }
	if ($i === 46) { return; }
	if ($i === 48) { return; }
	if ($i === 50) { return; }
	if ($i === 52) { return; }
	if ($i === 54) { return; }
	if ($i === 56) { return; }
	if ($i === 58) { return; }
	if ($i === 60) { return; }
	if ($i === 62) { return; }
	if ($i === 64) { return; }
	if ($i === 66) { return; }
	if ($i === 68) { return; }
	if ($i === 70) { return; }
	if ($i === 72) { return; }
	if ($i === 74) { return; }
	if ($i === 76) { return; }
	if ($i === 78) { return; }
	if ($i === 80) { return; }
	if ($i === 82) { return; }
	if ($i === 84) { return; }
	if ($i === 86) { return; }
	if ($i === 88) { return; }
	if ($i === 90) { return; }
	if ($i === 92) { return; }
	if ($i === 94) { return; }
	if ($i === 96) { return; }
	if ($i === 98) { return; }
	if ($i === 100) { return; }
	if ($i === 102) { return; }
	if ($i === 104) { return; }
	if ($i === 106) { return; }
	if ($i === 108) { return; }
	if ($i === 110) { return; }
	if ($i === 112) { return; }
	if ($i === 114) { return; }
	if ($i === 116) { return; }
	if ($i === 118) { return; }
	if ($i === 120) { return; }
	if ($i === 122) { return; }
	if ($i === 124) { return; }
	if ($i === 126) { return; }
	if ($i === 128) { return; }
	if ($i === 130) { return; }
	if ($i === 132) { return; }
	if ($i === 134) { return; }
	if ($i === 136) { return; }
	if ($i === 138) { return; }
	if ($i === 140) { return; }
	if ($i === 142) { return; }
	if ($i === 144) { return; }
	if ($i === 146) { return; }
	if ($i === 148) { return; }
	if ($i === 150) { return; }
	if ($i === 152) { return; }
	if ($i === 154) { return; }
	if ($i === 156) { return; }
	if ($i === 158) { return; }
	if ($i === 160) { return; }
	if ($i === 162) { return; }
	if ($i === 164) { return; }
	if ($i === 166) { return; }
	if ($i === 168) { return; }
	if ($i === 170) { return; }
	if ($i === 172) { return; }
	if ($i === 174) { return; }
	if ($i === 176) { return; }
	if ($i === 178) { return; }
	if ($i === 180) { return; }
	if ($i === 182) { return; }
	if ($i === 184) { return; }
	if ($i === 186) { return; }
	if ($i === 188) { return; }
	if ($i === 190) { return; }
	if ($i === 192) { return; }
	if ($i === 194) { return; }
	if ($i === 196) { return; }
	if ($i === 198) { return; }
	if ($i === 200) { return; }
	if ($i === 202) { return; }
	if ($i === 204) { return; }
	if ($i === 206) { return; }
	if ($i === 208) { return; }
	if ($i === 210) { return; }
	if ($i === 212) { return; }
	if ($i === 214) { return; }
	if ($i === 216) { return; }
	if ($i === 218) { return; }
	if ($i === 220) { return; }
	if ($i === 222) { return; }
	if ($i === 224) { return; }
	if ($i === 226) { return; }
	if ($i === 228) { return; }
	if ($i === 230) { return; }
	if ($i === 232) { return; }
	if ($i === 234) { return; }
	if ($i === 236) { return; }
	if ($i === 238) { return; }
	if ($i === 240) { return; }
	if ($i === 242) { return; }
	if ($i === 244) { return; }
	if ($i === 246) { return; }
	if ($i === 248) { return; }
	if ($i === 250) { return; }
	if ($i === 252) { return; }
	if ($i === 254) { return; }
	if ($i === 256) { return; }
	if ($i === 258) { return; }
	if ($i === 260) { return; }
	if ($i === 262) { return; }
	if ($i === 264) { return; }
	if ($i === 266) { return; }
	if ($i === 268) { return; }
	if ($i === 270) { return; }
	if ($i === 272) { return; }
	if ($i === 274) { return; }
	if ($i === 276) { return; }
	if ($i === 278) { return; }
	if ($i === 280) { return; }
	if ($i === 282) { return; }
	if ($i === 284) { return; }
	if ($i === 286) { return; }
	if ($i === 288) { return; }
	if ($i === 290) { return; }
	if ($i === 292) { return; }
	if ($i === 294) { return; }
	if ($i === 296) { return; }
	if ($i === 298) { return; }
	if ($i === 300) { return; }
	if ($i === 302) { return; }
	if ($i === 304) { return; }
	if ($i === 306) { return; }
	if ($i === 308) { return; }
	if ($i === 310) { return; }
	if ($i === 312) { return; }
	if ($i === 314) { return; }
	if ($i === 316) { return; }
	if ($i === 318) { return; }
	if ($i === 320) { return; }
	if ($i === 322) { return; }
	if ($i === 324) { return; }
	if ($i === 326) { return; }
	if ($i === 328) { return; }
	if ($i === 330) { return; }
	if ($i === 332) { return; }
	if ($i === 334) { return; }
	if ($i === 336) { return; }
	if ($i === 338) { return; }
	if ($i === 340) { return; }
	if ($i === 342) { return; }
	if ($i === 344) { return; }
	if ($i === 346) { return; }
	if ($i === 348) { return; }
	if ($i === 350) { return; }
	if ($i === 352) { return; }
	if ($i === 354) { return; }
	if ($i === 356) { return; }
	if ($i === 358) { return; }
	if ($i === 360) { return; }
	if ($i === 362) { return; }
	if ($i === 364) { return; }
	if ($i === 366) { return; }
	if ($i === 368) { return; }
	if ($i === 370) { return; }
	if ($i === 372) { return; }
	if ($i === 374) { return; }
	if ($i === 376) { return; }
	if ($i === 378) { return; }
	if ($i === 380) { return; }
	if ($i === 382) { return; }
	if ($i === 384) { return; }
	if ($i === 386) { return; }
	if ($i === 388) { return; }
	if ($i === 390) { return; }
	if ($i === 392) { return; }
	if ($i === 394) { return; }
	if ($i === 396) { return; }
	if ($i === 398) { return; }
	if ($i === 400) { return; }
	if ($i === 402) { return; }
	if ($i === 404) { return; }
	if ($i === 406) { return; }
	if ($i === 408) { return; }
	if ($i === 410) { return; }
	if ($i === 412) { return; }
	if ($i === 414) { return; }
	if ($i === 416) { return; }
	if ($i === 418) { return; }
	if ($i === 420) { return; }
	if ($i === 422) { return; }
	if ($i === 424) { return; }
	if ($i === 426) { return; }
	if ($i === 428) { return; }
	if ($i === 430) { return; }
	if ($i === 432) { return; }
	if ($i === 434) { return; }
	if ($i === 436) { return; }
	if ($i === 438) { return; }
	if ($i === 440) { return; }
	if ($i === 442) { return; }
	if ($i === 444) { return; }
	if ($i === 446) { return; }
	if ($i === 448) { return; }
	if ($i === 450) { return; }
	if ($i === 452) { return; }
	if ($i === 454) { return; }
	if ($i === 456) { return; }
	if ($i === 458) { return; }
	if ($i === 460) { return; }
	if ($i === 462) { return; }
	if ($i === 464) { return; }
	if ($i === 466) { return; }
	if ($i === 468) { return; }
	if ($i === 470) { return; }
	if ($i === 472) { return; }
	if ($i === 474) { return; }
	if ($i === 476) { return; }
	if ($i === 478) { return; }
	if ($i === 480) { return; }
	if ($i === 482) { return; }
	if ($i === 484) { return; }
	if ($i === 486) { return; }
	if ($i === 488) { return; }
	if ($i === 490) { return; }
	if ($i === 492) { return; }
	if ($i === 494) { return; }
	if ($i === 496) { return; }
	if ($i === 498) { return; }
	if ($i === 500) { return; }
	if ($i === 502) { return; }
	if ($i === 504) { return; }
	if ($i === 506) { return; }
	if ($i === 508) { return; }
	if ($i === 510) { return; }
	if ($i === 512) { return; }
	if ($i === 514) { return; }
	if ($i === 516) { return; }
	if ($i === 518) { return; }
	if ($i === 520) { return; }
	if ($i === 522) { return; }
	if ($i === 524) { return; }
	if ($i === 526) { return; }
	if ($i === 528) { return; }
	if ($i === 530) { return; }
	if ($i === 532) { return; }
	if ($i === 534) { return; }
	if ($i === 536) { return; }
	if ($i === 538) { return; }
	if ($i === 540) { return; }
	if ($i === 542) { return; }
	if ($i === 544) { return; }
	if ($i === 546) { return; }
	if ($i === 548) { return; }
	if ($i === 550) { return; }
	if ($i === 552) { return; }
	if ($i === 554) { return; }
	if ($i === 556) { return; }
	if ($i === 558) { return; }
	if ($i === 560) { return; }
	if ($i === 562) { return; }
	if ($i === 564) { return; }
	if ($i === 566) { return; }
	if ($i === 568) { return; }
	if ($i === 570) { return; }
	if ($i === 572) { return; }
	if ($i === 574) { return; }
	if ($i === 576) { return; }
	if ($i === 578) { return; }
	if ($i === 580) { return; }
	if ($i === 582) { return; }
	if ($i === 584) { return; }
	if ($i === 586) { return; }
	if ($i === 588) { return; }
	if ($i === 590) { return; }
	if ($i === 592) { return; }
	if ($i === 594) { return; }
	if ($i === 596) { return; }
	if ($i === 598) { return; }
	if ($i === 600) { return; }
	\PHPStan\dumpType($i);
}
