<?php
declare(strict_types=1);
set_error_handler(function ($no, $str) { echo "  [W] $str\n"; return true; });
function t(string $label, callable $f): void { echo $label, ' => '; try { $r = $f(); echo var_export($r, true), "\n"; } catch (\Throwable $e) { echo get_class($e), ': ', $e->getMessage(), "\n"; } }
echo PHP_VERSION, ' int size ', PHP_INT_SIZE, "\n";
t('(int)NAN', fn() => (int) NAN);
t('(int)INF', fn() => (int) INF);
t('(int)-INF', fn() => (int) -INF);
t('(int)1e19', fn() => (int) 1e19);
t('(int)-1e19', fn() => (int) -1e19);
t('(int)9223372036854775808.0', fn() => (int) 9223372036854775808.0);
t('(int)9223372036854775807.0', fn() => (int) 9223372036854775807.0);
t('(int)-9223372036854775808.0', fn() => (int) -9223372036854775808.0);
t('(string)NAN', fn() => (string) NAN);
t('(string)-NAN', fn() => (string) -NAN);
t('(bool)NAN', fn() => (bool) NAN);
t('(array)NAN', fn() => (array) NAN);
t('[NAN=>1]', fn() => [NAN => 1]);
t('[INF=>1]', fn() => [INF => 1]);
t('[1e19=>1]', fn() => [1e19 => 1]);
t('1 % NAN', fn() => 1 % NAN);
t('1 % INF', fn() => 1 % INF);
t('1 % 1e19', fn() => 1 % 1e19);
t('intdiv(1,(int)NAN)', fn() => intdiv(1, (int) NAN));
t('NAN===NAN', fn() => NAN === NAN);
t('NAN==NAN', fn() => NAN == NAN);
t('NAN<=>NAN', fn() => NAN <=> NAN);
t('1<=>NAN', fn() => 1 <=> NAN);
t('NAN<1', fn() => NAN < 1);
t('NAN>1', fn() => NAN > 1);
t('NAN>=NAN', fn() => NAN >= NAN);
t('-NAN===NAN', fn() => -NAN === NAN);
t('is_nan(-NAN)', fn() => is_nan(-NAN));
t('in_array(NAN,[NAN],true)', fn() => in_array(NAN, [NAN], true));
t('in_array(NAN,[NAN])', fn() => in_array(NAN, [NAN]));
t('[NAN]===[NAN]', fn() => [NAN] === [NAN]);
t('$a=[NAN]; $a===$a', function() { $a = [NAN]; return $a === $a; });
t('array_search(NAN,[NAN],true)', fn() => array_search(NAN, [NAN], true));
t('match(NAN){NAN=>1,default=>0}', fn() => match (NAN) { NAN => 1, default => 0 });
t('switch NAN case NAN', function() { switch (NAN) { case NAN: return 'nan'; default: return 'def'; } });
t('is_finite("1e500")', fn() => is_finite("1e500"));
t('is_infinite("1e500")', fn() => is_infinite("1e500"));
t('is_nan("abc")', fn() => is_nan("abc"));
t('is_nan(1)', fn() => is_nan(1));
t('is_finite(1)', fn() => is_finite(1));
t('is_finite("1")', fn() => is_finite("1"));
t('is_finite(true)', fn() => is_finite(true));
t('is_finite(null)', fn() => is_finite(null));
t('is_nan(null)', fn() => is_nan(null));
t('is_nan("NAN")', fn() => is_nan("NAN"));
t('is_nan("nan")', fn() => is_nan("nan"));
t('max(NAN,1)', fn() => max(NAN, 1));
t('max(1,NAN)', fn() => max(1, NAN));
t('min(NAN,1)', fn() => min(NAN, 1));
t('min(1,NAN)', fn() => min(1, NAN));
t('abs(NAN)', fn() => abs(NAN));
t('round(NAN)', fn() => round(NAN));
t('NAN ?: "x"', fn() => NAN ?: 'x');
t('!NAN', fn() => !NAN);
t('NAN == 0.0', fn() => NAN == 0.0);
t('NAN == "NAN"', fn() => NAN == "NAN");
t('NAN == true', fn() => NAN == true);
t('NAN == null', fn() => NAN == null);
t('INF == "INF"', fn() => INF == "INF");
t('json_encode(NAN)', fn() => json_encode(NAN));
t('var_export(NAN,true)', fn() => var_export(NAN, true));
t('0.0*INF', fn() => 0.0 * INF);
t('INF-INF', fn() => INF - INF);
t('fdiv(0,0)', fn() => fdiv(0, 0));
t('sqrt(-1.0)', fn() => sqrt(-1.0));
t('(float)PHP_INT_MAX === PHP_INT_MAX + 1.0', fn() => (float) PHP_INT_MAX === PHP_INT_MAX + 1.0);
t('9223372036854775807.0 == PHP_INT_MAX', fn() => 9223372036854775807.0 == PHP_INT_MAX);
t('PHP_INT_MAX < 9223372036854775808.0', fn() => PHP_INT_MAX < 9223372036854775808.0);
t('-0.0 === 0.0', fn() => -0.0 === 0.0);
t('(string)-0.0', fn() => (string) -0.0);
t('[-0.0 => 1] key', fn() => array_keys([-0.0 => 1]));
t('1.5 <=> "1.5"', fn() => 1.5 <=> "1.5");
t('NAN ** 0', fn() => NAN ** 0);
t('1 ** NAN', fn() => 1 ** NAN);
t('str_repeat("x", NAN) strict', fn() => str_repeat('x', NAN));
t('range(0, NAN)', fn() => range(0, NAN));
t('array_fill(0, NAN, 1)', fn() => array_fill(0, NAN, 1));
t('filter_var(NAN, FILTER_VALIDATE_INT)', fn() => filter_var(NAN, FILTER_VALIDATE_INT));
t('filter_var(INF, FILTER_VALIDATE_INT)', fn() => filter_var(INF, FILTER_VALIDATE_INT));
t('filter_var(1e19, FILTER_VALIDATE_INT)', fn() => filter_var(1e19, FILTER_VALIDATE_INT));
t('settype NAN int', function() { $x = NAN; settype($x, 'int'); return $x; });
t('~NAN', fn() => ~NAN);
t('NAN & 1', fn() => NAN & 1);
t('NAN << 1', fn() => NAN << 1);
t('intval(NAN)', fn() => intval(NAN));
t('sprintf("%d", NAN)', fn() => sprintf('%d', NAN));
t('number_format(NAN)', fn() => number_format(NAN));
t('(int)"1e19"', fn() => (int) "1e19");
t('1e19 == "1e19"', fn() => 1e19 == "1e19");
t('PHP_FLOAT_MAX + PHP_FLOAT_MAX', fn() => PHP_FLOAT_MAX + PHP_FLOAT_MAX);
t('5e-324 / 2', fn() => 5e-324 / 2);
t('nextafter-ish: 1.0 + PHP_FLOAT_EPSILON', fn() => 1.0 + PHP_FLOAT_EPSILON);
