<?php declare(strict_types = 1);

$root = $argv[1];
require $root . '/vendor/autoload.php';

use PHPStan\Type\Constant\ConstantFloatType;
use PHPStan\Type\Constant\ConstantIntegerType;
use PHPStan\Type\FloatRangeType;
use PHPStan\Type\FloatType;
use PHPStan\Type\IntegerRangeType;
use PHPStan\Type\IntegerType;
use PHPStan\Type\NullType;
use PHPStan\Type\MixedType;
use PHPStan\Type\UnionType;
use PHPStan\Type\TypeCombinator;
use PHPStan\Type\VerbosityLevel;
use PHPStan\Type\Generic\TemplateTypeFactory;
use PHPStan\Type\Generic\TemplateTypeScope;
use PHPStan\Type\Generic\TemplateTypeVariance;

$p = VerbosityLevel::precise();
$scope = TemplateTypeScope::createWithFunction('foo');
$tFloat = TemplateTypeFactory::create($scope, 'T', new FloatType(), TemplateTypeVariance::createInvariant());
$tInt = TemplateTypeFactory::create($scope, 'U', new IntegerType(), TemplateTypeVariance::createInvariant());
$fr = FloatRangeType::fromInterval(0.0, 1.0);
$ir = IntegerRangeType::fromInterval(0, 1);
$nonNan = FloatRangeType::fromInterval(-INF, INF);

echo "float<0,1>->isSubTypeOf(T of float)     : ", $fr->isSubTypeOf($tFloat)->describe(), PHP_EOL;
echo "int<0,1>->isSubTypeOf(U of int)         : ", $ir->isSubTypeOf($tInt)->describe(), PHP_EOL;
echo "T of float ->isSuperTypeOf(float<0,1>)  : ", $tFloat->isSuperTypeOf($fr)->describe(), PHP_EOL;
echo "U of int   ->isSuperTypeOf(int<0,1>)    : ", $tInt->isSuperTypeOf($ir)->describe(), PHP_EOL;
$tFloatOrNull = new UnionType([$tFloat, new NullType()]);
$tIntOrNull = new UnionType([$tInt, new NullType()]);
echo "(T of float)|null ->isSuperTypeOf(float<0,1>): ", $tFloatOrNull->isSuperTypeOf($fr)->describe(), PHP_EOL;
echo "(U of int)|null   ->isSuperTypeOf(int<0,1>)  : ", $tIntOrNull->isSuperTypeOf($ir)->describe(), PHP_EOL;
echo "remove(float<0,1>, (T of float)|null)   : ", TypeCombinator::remove($fr, $tFloatOrNull)->describe($p), PHP_EOL;
echo "remove(int<0,1>, (U of int)|null)       : ", TypeCombinator::remove($ir, $tIntOrNull)->describe($p), PHP_EOL;
echo "float<0,1>->isSubTypeOf(mixed)          : ", $fr->isSubTypeOf(new MixedType())->describe(), PHP_EOL;
echo "int<0,1>->isSubTypeOf(mixed)            : ", $ir->isSubTypeOf(new MixedType())->describe(), PHP_EOL;
echo "float<0,1>->isAcceptedBy(mixed)         : ", $fr->isAcceptedBy(new MixedType(), true)->result->describe(), PHP_EOL;
echo "float<0,1>->isAcceptedBy(T of float)    : ", $fr->isAcceptedBy($tFloat, true)->result->describe(), PHP_EOL;
echo "int<0,1>->isAcceptedBy(U of int)        : ", $ir->isAcceptedBy($tInt, true)->result->describe(), PHP_EOL;

echo "--- intersect order ---", PHP_EOL;
echo "intersect(0.5, float<0,1>)  : ", TypeCombinator::intersect(new ConstantFloatType(0.5), $fr)->describe($p), PHP_EOL;
echo "intersect(float<0,1>, 0.5)  : ", TypeCombinator::intersect($fr, new ConstantFloatType(0.5))->describe($p), PHP_EOL;
echo "intersect(1.5, float<0,1>)  : ", TypeCombinator::intersect(new ConstantFloatType(1.5), $fr)->describe($p), PHP_EOL;
echo "intersect(NAN, float<0,1>)  : ", TypeCombinator::intersect(new ConstantFloatType(NAN), $fr)->describe($p), PHP_EOL;
echo "intersect(float, float<0,1>): ", TypeCombinator::intersect(new FloatType(), $fr)->describe($p), PHP_EOL;
echo "intersect(float<0,1>, float<0.5,2>) : ", TypeCombinator::intersect($fr, FloatRangeType::fromInterval(0.5, 2.0))->describe($p), PHP_EOL;
echo "intersect(float<0.5,2>, float<0,1>) : ", TypeCombinator::intersect(FloatRangeType::fromInterval(0.5, 2.0), $fr)->describe($p), PHP_EOL;
echo "intersect(float<0,1>, int<0,1>)     : ", TypeCombinator::intersect($fr, $ir)->describe($p), PHP_EOL;
echo "intersect(float<0,1>, int)          : ", TypeCombinator::intersect($fr, new IntegerType())->describe($p), PHP_EOL;

echo "--- equals / describe / union consistency ---", PHP_EOL;
$a = FloatRangeType::fromInterval(0.0, 1.0, minInclusive: false);
$b = FloatRangeType::fromInterval(5.0E-324, 1.0);
echo "a=", $a->describe($p), " b=", $b->describe($p), " equals=", var_export($a->equals($b), true), PHP_EOL;
echo "union(a, b) = ", TypeCombinator::union($a, $b)->describe($p), PHP_EOL;
echo "union(b, a) = ", TypeCombinator::union($b, $a)->describe($p), PHP_EOL;
echo "union(nonNan, NAN) = ", TypeCombinator::union($nonNan, new ConstantFloatType(NAN))->describe($p), " equals float? ", var_export(TypeCombinator::union($nonNan, new ConstantFloatType(NAN))->equals(new FloatType()), true), PHP_EOL;
echo "union((-inf,inf), -INF, INF, NAN) = ", TypeCombinator::union(FloatRangeType::createFinite(), new ConstantFloatType(-INF), new ConstantFloatType(INF), new ConstantFloatType(NAN))->describe($p), PHP_EOL;
echo "union(NAN, (-inf,inf), INF, -INF) = ", TypeCombinator::union(new ConstantFloatType(NAN), FloatRangeType::createFinite(), new ConstantFloatType(INF), new ConstantFloatType(-INF))->describe($p), PHP_EOL;
echo "union(int, nonNan, NAN) = ", TypeCombinator::union(new IntegerType(), $nonNan, new ConstantFloatType(NAN))->describe($p), PHP_EOL;
echo "union(NAN, int, nonNan) = ", TypeCombinator::union(new ConstantFloatType(NAN), new IntegerType(), $nonNan)->describe($p), PHP_EOL;
echo "union(nonNan|int, NAN) = ", TypeCombinator::union(new UnionType([$nonNan, new IntegerType()]), new ConstantFloatType(NAN))->describe($p), PHP_EOL;
echo "union(NAN|int, nonNan) = ", TypeCombinator::union(new UnionType([new ConstantFloatType(NAN), new IntegerType()]), $nonNan)->describe($p), PHP_EOL;
echo "remove(float|int, NAN) = ", TypeCombinator::remove(new UnionType([new FloatType(), new IntegerType()]), new ConstantFloatType(NAN))->describe($p), PHP_EOL;
echo "remove(float, NAN|INF) = ", TypeCombinator::remove(new FloatType(), new UnionType([new ConstantFloatType(NAN), new ConstantFloatType(INF)]))->describe($p), PHP_EOL;
echo "remove(float, 0.0|NAN) = ", TypeCombinator::remove(new FloatType(), new UnionType([new ConstantFloatType(0.0), new ConstantFloatType(NAN)]))->describe($p), PHP_EOL;
echo "remove(float, NAN|0.0) = ", TypeCombinator::remove(new FloatType(), new UnionType([new ConstantFloatType(NAN), new ConstantFloatType(0.0)]))->describe($p), PHP_EOL;
echo "remove(nonNan, 0.0) = ", TypeCombinator::remove($nonNan, new ConstantFloatType(0.0))->describe($p), PHP_EOL;
echo "remove(float, 0.0) = ", TypeCombinator::remove(new FloatType(), new ConstantFloatType(0.0))->describe($p), PHP_EOL;
echo "remove(mixed, NAN) = ", TypeCombinator::remove(new MixedType(), new ConstantFloatType(NAN))->describe($p), PHP_EOL;
echo "intersect(mixed~NAN, float) = ", TypeCombinator::intersect(TypeCombinator::remove(new MixedType(), new ConstantFloatType(NAN)), new FloatType())->describe($p), PHP_EOL;
echo "intersect(mixed~float<-inf,inf>, float) = ", TypeCombinator::intersect(TypeCombinator::remove(new MixedType(), $nonNan), new FloatType())->describe($p), PHP_EOL;
echo "nonNan->isSuperTypeOf(float) = ", $nonNan->isSuperTypeOf(new FloatType())->describe(), PHP_EOL;
echo "float->isSuperTypeOf(nonNan) = ", (new FloatType())->isSuperTypeOf($nonNan)->describe(), PHP_EOL;
echo "nonNan->accepts(float) = ", $nonNan->accepts(new FloatType(), true)->result->describe(), PHP_EOL;
echo "NAN->isSuperTypeOf(nonNan) = ", (new ConstantFloatType(NAN))->isSuperTypeOf($nonNan)->describe(), PHP_EOL;
echo "nonNan->isSuperTypeOf(NAN) = ", $nonNan->isSuperTypeOf(new ConstantFloatType(NAN))->describe(), PHP_EOL;
echo "NAN->equals(NAN) = ", var_export((new ConstantFloatType(NAN))->equals(new ConstantFloatType(NAN)), true), PHP_EOL;
echo "NAN->isSuperTypeOf(NAN) = ", (new ConstantFloatType(NAN))->isSuperTypeOf(new ConstantFloatType(NAN))->describe(), PHP_EOL;
echo "NAN->accepts(NAN) = ", (new ConstantFloatType(NAN))->accepts(new ConstantFloatType(NAN), true)->result->describe(), PHP_EOL;
echo "toString: nonNan=", $nonNan->toString()->describe($p), " finite=", FloatRangeType::createFinite()->toString()->describe($p), " INF=", (new ConstantFloatType(INF))->toString()->describe($p), " NAN=", (new ConstantFloatType(NAN))->toString()->describe($p), PHP_EOL;
echo "toInteger: nonNan=", $nonNan->toInteger()->describe($p), " INF=", (new ConstantFloatType(INF))->toInteger()->describe($p), " 1e19=", (new ConstantFloatType(1e19))->toInteger()->describe($p), " 2^63=", (new ConstantFloatType(PHP_INT_MAX + 1.0))->toInteger()->describe($p), " -2^63=", (new ConstantFloatType((float) PHP_INT_MIN))->toInteger()->describe($p), PHP_EOL;
echo "toArrayKey NAN=", (new ConstantFloatType(NAN))->toArrayKey()->describe($p), " toBoolean NAN=", (new ConstantFloatType(NAN))->toBoolean()->describe($p), " toAbs NAN=", (new ConstantFloatType(NAN))->toAbsoluteNumber()->describe($p), PHP_EOL;
echo "generalize nonNan=", $nonNan->generalize(\PHPStan\Type\GeneralizePrecision::lessSpecific())->describe($p), PHP_EOL;
echo "toPhpDocNode nonNan=", (string) $nonNan->toPhpDocNode(), " finite=", (string) FloatRangeType::createFinite()->toPhpDocNode(), PHP_EOL;
echo "getFiniteTypes NAN=", count((new ConstantFloatType(NAN))->getFiniteTypes()), " INF=", count((new ConstantFloatType(INF))->getFiniteTypes()), PHP_EOL;
echo "describe(typeOnly) nonNan=", $nonNan->describe(VerbosityLevel::typeOnly()), " value=", $nonNan->describe(VerbosityLevel::value()), PHP_EOL;
echo "toCoercedArgumentType(nonNan, false)=", $nonNan->toCoercedArgumentType(false)->describe($p), PHP_EOL;
echo "toCoercedArgumentType(float, false)=", (new FloatType())->toCoercedArgumentType(false)->describe($p), PHP_EOL;
echo "float<0,1>->toCoercedArgumentType(false)=", $fr->toCoercedArgumentType(false)->describe($p), PHP_EOL;
echo "--- template soundness ---", PHP_EOL;
echo "T of float ->accepts(float<0,1>)        : ", $tFloat->accepts($fr, true)->result->describe(), PHP_EOL;
echo "U of int   ->accepts(int<0,1>)          : ", $tInt->accepts($ir, true)->result->describe(), PHP_EOL;
echo "T of float ->accepts(nonNan)            : ", $tFloat->accepts($nonNan, true)->result->describe(), PHP_EOL;
echo "T of float ->accepts(float)             : ", $tFloat->accepts(new FloatType(), true)->result->describe(), PHP_EOL;
echo "T of float ->accepts(1.5)               : ", $tFloat->accepts(new ConstantFloatType(1.5), true)->result->describe(), PHP_EOL;
echo "T of float ->isSuperTypeOf(nonNan)      : ", $tFloat->isSuperTypeOf($nonNan)->describe(), PHP_EOL;
echo "T of float ->isSuperTypeOf(float)       : ", $tFloat->isSuperTypeOf(new FloatType())->describe(), PHP_EOL;
echo "T of float ->isSuperTypeOf(1.5)         : ", $tFloat->isSuperTypeOf(new ConstantFloatType(1.5))->describe(), PHP_EOL;
echo "nonNan->isSubTypeOf(T of float)         : ", $nonNan->isSubTypeOf($tFloat)->describe(), PHP_EOL;
echo "nonNan->isSubTypeOf(T of float | int)   : ", $nonNan->isSubTypeOf(new UnionType([$tFloat, new IntegerType()]))->describe(), PHP_EOL;
$tMixed = TemplateTypeFactory::create($scope, 'M', new MixedType(), TemplateTypeVariance::createInvariant());
echo "M of mixed ->accepts(float<0,1>)        : ", $tMixed->accepts($fr, true)->result->describe(), PHP_EOL;
echo "M of mixed ->accepts(int<0,1>)          : ", $tMixed->accepts($ir, true)->result->describe(), PHP_EOL;
echo "M of mixed ->isSuperTypeOf(float<0,1>)  : ", $tMixed->isSuperTypeOf($fr)->describe(), PHP_EOL;
echo "M of mixed ->isSuperTypeOf(int<0,1>)    : ", $tMixed->isSuperTypeOf($ir)->describe(), PHP_EOL;
$tFloatOrInt = TemplateTypeFactory::create($scope, 'N', new UnionType([new FloatType(), new IntegerType()]), TemplateTypeVariance::createInvariant());
echo "N of float|int ->accepts(float<0,1>)    : ", $tFloatOrInt->accepts($fr, true)->result->describe(), PHP_EOL;
echo "N of float|int ->accepts(int<0,1>)      : ", $tFloatOrInt->accepts($ir, true)->result->describe(), PHP_EOL;
echo "N of float|int ->isSuperTypeOf(float<0,1>): ", $tFloatOrInt->isSuperTypeOf($fr)->describe(), PHP_EOL;
echo "--- toString soundness ---", PHP_EOL;
echo "nonNan->toString()  : ", $nonNan->toString()->describe($p), PHP_EOL;
echo "finite->toString()  : ", FloatRangeType::createFinite()->toString()->describe($p), PHP_EOL;
echo "INF->toString()     : ", (new ConstantFloatType(INF))->toString()->describe($p), " isNumericString=", (new ConstantFloatType(INF))->toString()->isNumericString()->describe(), PHP_EOL;
echo "float->toString()   : ", (new FloatType())->toString()->describe($p), PHP_EOL;
echo "--- unary minus / abs on asymmetric ranges (via toAbsoluteNumber only; unary minus lives in resolver) ---", PHP_EOL;
$asym = FloatRangeType::fromInterval(-INF, 0.5, true, false);
echo "asym = ", $asym->describe($p), " abs=", $asym->toAbsoluteNumber()->describe($p), " toInteger=", $asym->toInteger()->describe($p), " toBoolean=", $asym->toBoolean()->describe($p), PHP_EOL;
echo "--- sort determinism ---", PHP_EOL;
$mix = [IntegerRangeType::fromInterval(0, 5), FloatRangeType::fromInterval(0.0, 1.0), new ConstantFloatType(NAN), new ConstantIntegerType(7), new ConstantFloatType(2.5), FloatRangeType::fromInterval(3.0, 4.0), new \PHPStan\Type\StringType(), new NullType()];
for ($i = 0; $i < 5; $i++) { shuffle($mix); echo TypeCombinator::union(...$mix)->describe($p), PHP_EOL; }
