<?php declare(strict_types = 1);
$root = $argv[1];
require $root . '/vendor/autoload.php';
use PHPStan\Php\PhpVersion;
use PHPStan\Type\Constant\ConstantFloatType;
use PHPStan\Type\Constant\ConstantIntegerType;
use PHPStan\Type\IntegerRangeType;
use PHPStan\Type\FloatType;
use PHPStan\Type\MixedType;
use PHPStan\Type\TypeCombinator;
use PHPStan\Type\VerbosityLevel;
$p = VerbosityLevel::precise();
$warnings = [];
set_error_handler(function (int $no, string $str, string $file, int $line) use (&$warnings): bool { $warnings[] = $str . ' @ ' . basename($file) . ':' . $line; return true; });
function t(string $label, callable $f): void {
	global $warnings, $p;
	$warnings = [];
	try { $r = $f(); $out = $r instanceof \PHPStan\Type\Type ? $r->describe($p) : var_export($r, true); }
	catch (\Throwable $e) { $out = get_class($e) . ': ' . $e->getMessage(); }
	printf("%-58s => %-40s %s\n", $label, $out, $warnings === [] ? '' : '[W] ' . implode(' | ', $warnings));
}
$v = new PhpVersion(80500);
$nan = new ConstantFloatType(NAN); $inf = new ConstantFloatType(INF); $big = new ConstantFloatType(1e19); $two63 = new ConstantFloatType(9223372036854775808.0);
t('NAN->toInteger()', fn() => $nan->toInteger());
t('NAN->toString()', fn() => $nan->toString());
t('NAN->toBoolean()', fn() => $nan->toBoolean());
t('NAN->toArrayKey()', fn() => $nan->toArrayKey());
t('NAN->toBitwiseNotType()', fn() => $nan->toBitwiseNotType());
t('INF->toInteger()', fn() => $inf->toInteger());
t('1e19->toInteger()', fn() => $big->toInteger());
t('2^63->toInteger()', fn() => $two63->toInteger());
t('2^63->getGreaterOrEqualType()', fn() => $two63->getGreaterOrEqualType($v));
t('2^63->getSmallerType()', fn() => $two63->getSmallerType($v));
t('2^63->getSmallerOrEqualType()', fn() => $two63->getSmallerOrEqualType($v));
t('2^63->getGreaterType()', fn() => $two63->getGreaterType($v));
t('1e19->getGreaterType()', fn() => $big->getGreaterType($v));
t('NAN->getSmallerType()', fn() => $nan->getSmallerType($v));
t('NAN->getSmallerOrEqualType()', fn() => $nan->getSmallerOrEqualType($v));
t('NAN->getGreaterType()', fn() => $nan->getGreaterType($v));
t('NAN->getGreaterOrEqualType()', fn() => $nan->getGreaterOrEqualType($v));
t('createAllSmallerThan(NAN)', fn() => IntegerRangeType::createAllSmallerThan(NAN));
t('createAllSmallerThanOrEqualTo(NAN)', fn() => IntegerRangeType::createAllSmallerThanOrEqualTo(NAN));
t('createAllGreaterThan(NAN)', fn() => IntegerRangeType::createAllGreaterThan(NAN));
t('createAllGreaterThanOrEqualTo(NAN)', fn() => IntegerRangeType::createAllGreaterThanOrEqualTo(NAN));
t('createAllSmallerThan(INF)', fn() => IntegerRangeType::createAllSmallerThan(INF));
t('createAllGreaterThan(-INF)', fn() => IntegerRangeType::createAllGreaterThan(-INF));
t('createAllSmallerThan(2^63)', fn() => IntegerRangeType::createAllSmallerThan(9223372036854775808.0));
t('createAllGreaterThanOrEqualTo(2^63)', fn() => IntegerRangeType::createAllGreaterThanOrEqualTo(9223372036854775808.0));
t('createAllSmallerThanOrEqualTo(-2^63)', fn() => IntegerRangeType::createAllSmallerThanOrEqualTo(-9223372036854775808.0));
t('createAllGreaterThan(-2^63)', fn() => IntegerRangeType::createAllGreaterThan(-9223372036854775808.0));
t('ConstantFloat(-2^63)->getGreaterType()', fn() => (new ConstantFloatType(-9223372036854775808.0))->getGreaterType($v));
t('NAN->isSmallerThan(1)', fn() => $nan->isSmallerThan(new ConstantIntegerType(1), $v));
t('NAN->looseCompare(true)', fn() => $nan->looseCompare(new \PHPStan\Type\Constant\ConstantBooleanType(true), $v));
t('NAN->looseCompare("NAN")', fn() => $nan->looseCompare(new \PHPStan\Type\Constant\ConstantStringType('NAN'), $v));
t('NAN->toAbsoluteNumber()', fn() => $nan->toAbsoluteNumber());
t('NAN->toNumber()', fn() => $nan->toNumber());
t('NAN->toFloat()', fn() => $nan->toFloat());
t('NAN->toArray()', fn() => $nan->toArray());
t('NAN->generalize()', fn() => $nan->generalize(\PHPStan\Type\GeneralizePrecision::lessSpecific()));
t('NAN->toPhpDocNode()', fn() => (string) $nan->toPhpDocNode());
t('(-NAN)->equals(NAN)', fn() => (new ConstantFloatType(-NAN))->equals($nan));
t('NAN->isSuperTypeOf(NAN)', fn() => $nan->isSuperTypeOf(new ConstantFloatType(NAN)));
t('NAN->accepts(NAN)', fn() => $nan->accepts(new ConstantFloatType(NAN), true));
t('union(NAN, NAN)', fn() => TypeCombinator::union($nan, new ConstantFloatType(NAN)));
t('union(NAN, -NAN)', fn() => TypeCombinator::union($nan, new ConstantFloatType(-NAN)));
t('remove(NAN, NAN)', fn() => TypeCombinator::remove($nan, new ConstantFloatType(NAN)));
t('remove(NAN|1.0, NAN)', fn() => TypeCombinator::remove(TypeCombinator::union($nan, new ConstantFloatType(1.0)), new ConstantFloatType(NAN)));
t('remove(1.0|NAN|null, NAN)', fn() => TypeCombinator::remove(TypeCombinator::union($nan, new ConstantFloatType(1.0), new \PHPStan\Type\NullType()), new ConstantFloatType(NAN)));
t('NAN->getFiniteTypes()', fn() => count($nan->getFiniteTypes()));
t('(1.0|NAN)->getFiniteTypes()', fn() => count(TypeCombinator::union($nan, new ConstantFloatType(1.0))->getFiniteTypes()));
t('intersect(NAN, float)', fn() => TypeCombinator::intersect($nan, new FloatType()));
t('union(0.0, -0.0)', fn() => TypeCombinator::union(new ConstantFloatType(0.0), new ConstantFloatType(-0.0)));
t('(-0.0)->describe', fn() => new ConstantFloatType(-0.0));
t('(-0.0)->toString()', fn() => (new ConstantFloatType(-0.0))->toString());
